// Fallback projects when Sanity returns empty.
// Shape matches generatedSanitySchemaTypes.ts / Project interface
// so the existing frontend components work without changes.
export const FALLBACK_PROJECTS = [
  {
    _type: 'project',
    _id: 'fallback-vfx',
    title: 'Visual Effects',
    shortTitle: 'VFX',
    slug: { _type: 'slug', current: 'vfx' },
    subTitle: 'Motion design & compositing',
    description: 'One of my latest AMV/VFX edits. I mixed 3D, mograph, and glitch transitions in this one.',
    client: 'Personal',
    color1: { hex: '#C39040' },
    gifUrl: '/videos/DisorderDisbeliefDiscombobulation.gif',
    links: [
      { text: 'Watch on YouTube', url: 'https://www.youtube.com/watch?v=L8YpgOelN4k' },
    ],
  },
  {
    _type: 'project',
    _id: 'fallback-photography',
    title: 'Photography',
    shortTitle: 'Photo',
    slug: { _type: 'slug', current: 'photography' },
    subTitle: 'Urban architecture & street photography',
    description: 'Practice shoot and edit. I was trying to make it feel nostalgic, like a memory.',
    client: 'Personal',
    color1: { hex: '#7F4D0F' },
    gifUrl: '/videos/Felt.gif',
    links: [
      { text: 'Watch on YouTube', url: 'https://www.youtube.com/watch?v=yM-kTk6Zdes' },
    ],
  },
  {
    _type: 'project',
    _id: 'fallback-fir4s-com',
    title: 'fir4s.com',
    shortTitle: 'Portfolio',
    slug: { _type: 'slug', current: 'fir4s-com' },
    subTitle: 'Personal portfolio website',
    description: 'My old personal site. I built it to feel like Windows XP.',
    client: 'Self',
    color1: { hex: '#534328' },
    gifUrl: '/videos/old-personal-website.gif',
    links: [
      { text: 'Visit site', url: '/old-site' },
    ],
  },
  {
    _type: 'project',
    _id: 'fallback-blank-1',
    title: 'Untitled',
    shortTitle: 'TBD',
    slug: { _type: 'slug', current: 'blank-1' },
    subTitle: 'Coming soon',
    description: 'Placeholder project slot (coming soon).',
    client: '-',
    color1: { hex: '#274757' },
    gifUrl: '',
  },
  {
    _type: 'project',
    _id: 'fallback-blank-2',
    title: 'Untitled',
    shortTitle: 'TBD',
    slug: { _type: 'slug', current: 'blank-2' },
    subTitle: 'Coming soon',
    description: 'Placeholder project slot (coming soon).',
    client: '-',
    color1: { hex: '#BAB5B2' },
    gifUrl: '',
  },
];
